obj=alloc_arr.o print_annotation.o in_param.o fill_arr.o print_arr.o merge_sort.o my_getch.o yes_no.o my_getch.o write_to_file.o insert_sort.o 
merge_with_insert: main.c $(obj)
	gcc $^ -o $@ -lm

clean:
	rm *.o
